# syntax=docker/dockerfile:1
FROM node:20-alpine AS build-step
WORKDIR /app

COPY pibitstream/package*.json ./
RUN npm ci

COPY ./pibitstream ./
RUN npm run build

# Build step #2: build an nginx container
FROM nginx:alpine

COPY --from=build-step /app/dist /usr/share/nginx/html
COPY ./pibitstream/deployment/nginx.default.conf /etc/nginx/conf.d/default.conf
