FROM node:22-bookworm
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      openfpgaloader \
      && rm -rf /var/lib/apt/lists/*

# Since we're inside backend/, just copy the files directly
COPY package.json ./
COPY package-lock.json ./

# Copy the rest of the backend source
COPY . ./

# Install dependencies
RUN npm ci

ENV NODE_ENV=production
ENV PORT=5000

EXPOSE 5000

CMD ["npm", "run", "start"]
