FROM node:22-alpine
WORKDIR /app

# Since we're inside backend/, just copy the files directly
COPY package.json ./
COPY package-lock.json ./

# Copy the rest of the backend source
COPY . ./

# Install dependencies
RUN npm ci

EXPOSE 5000

CMD ["npm", "run", "start"]
